export enum AnvilMode {
    Polygon = 'polygon',
    Polyline = 'polyline',
    Marker = 'marker',
    Rectangle = 'rectangle',
    Square = 'square',
    Triangle = 'triangle',
    Circle = 'circle',
    Freehand = 'freehand',
    Cut = 'cut',
    Split = 'split',
    Drag = 'drag',
    Scale = 'scale',
    Rotate = 'rotate',
    Union = 'union',
    Subtract = 'subtract',
    Edit = 'edit',
    Delete = 'delete',
    Off = 'off'
}
